version: '3'

services:
  mongo-0:
    image: mongo
    command: --replSet rs0 --oplogSize 128
    ports:
      - 27017:27017
    depends_on:
      - mongo-1
      - mongo-2

  mongo-1:
    image: mongo
    command: --replSet rs0 --oplogSize 128
    ports:
      - 27018:27017

  mongo-2:
    image: mongo
    command: --replSet rs0 --oplogSize 1
    ports:
      - 27019:27017

  setup:
    image: "setup"
    build:
      context: .
      dockerfile: Dockerfile.setup
    depends_on:
      - mongo-0

  admin:
    image: mrvautin/adminmongo
    restart: always
    environment:
      - HOST=0.0.0.0
    ports:
      - 1234:1234
